version: "3.9"
services:
  nginx:
    image: lab.knrg.su:5000/iskonstantin/moneysaver-nginx:master
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    networks:
      msnet:
          aliases:
            - nginx
  frontend:
    image: lab.knrg.su:5000/iskonstantin/moneysaver-frontend:master
    environment:
      BASE_URL: ${BASE_URL}
    ports:
      - "3000:3000"
    networks:
      msnet:
          aliases:
            - frontend
  backend:
    image: lab.knrg.su:5000/iskonstantin/moneysaver-backend:master
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      BASE_URL: ${BASE_URL}
    ports:
      - "8080:8080"
    volumes:
      - /etc/ms/backend:/ms/config
      - /var/log/ms:/ms/logs
    networks:
      msnet:
          aliases:
            - backend
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "money_saver"
      POSTGRES_USER: "money_saver"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
      BASE_URL: ${BASE_URL}
    volumes:
      - /var/lib/ms/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      msnet:
          aliases:
            - database
networks:
  msnet: